stages:
  - build
  - check
  - test

build website:
  image: node:20-alpine
  stage: build
  script:
    - yarn install
    - yarn build


  artifacts:
        paths:
            - build

check folder:
  image: alpine
  stage: check
  script:
    - test -f build/index.html





test job:
  image: node:20-alpine
  stage: test
  script:
    - yarn install
    - yarn test